[package]
name = "keycloak_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
keycloak = "26.2.0"
actix-web-middleware-keycloak-auth = "0.5.0"
actix-web = "4.10.2"
serde = "1.0.219"
jsonwebtoken = "9.3.1"
